version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: CalaClara21.
    volumes:
      - ./postgresData:/var/lib/postgresql/data
    ports:
      - 5432:5432
